//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class EditableOrdersGrid
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private EditableOrdersGrid() : base("LightSwitchApplication:EditableOrdersGrid")
        {
            global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static EditableOrdersGrid CreateInstance()
        {
            return new global::LightSwitchApplication.EditableOrdersGrid(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditableOrdersGrid_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Orders_SelectionChanged();

        partial void Orders_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Orders_Loaded(bool succeeded);

        partial void Approvals_SelectionChanged();

        partial void Approvals_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Approvals_Loaded(bool succeeded);

        partial void Approvals1_SelectionChanged();

        partial void Approvals1_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Approvals1_Loaded(bool succeeded);

        partial void OrderCurrencyConversions_SelectionChanged();

        partial void OrderCurrencyConversions_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderCurrencyConversions_Loaded(bool succeeded);

        partial void CompactingJoes_SelectionChanged();

        partial void CompactingJoes_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompactingJoes_Loaded(bool succeeded);

        partial void CompactingJoes1_SelectionChanged();

        partial void CompactingJoes1_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompactingJoes1_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Orders visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Order> Orders
        {
            get
            {
                return global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Orders);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Orders_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Approvals visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Approval> Approvals
        {
            get
            {
                return global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Approvals);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Approvals_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Approvals1 visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Approval> Approvals1
        {
            get
            {
                return global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Approvals1);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Approvals1_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the OrderCurrencyConversions visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.OrderCurrencyConversion> OrderCurrencyConversions
        {
            get
            {
                return global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.OrderCurrencyConversions);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderCurrencyConversions_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the CompactingJoes visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.CompactingJo> CompactingJoes
        {
            get
            {
                return global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.CompactingJoes);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompactingJoes_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the CompactingJoes1 visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.CompactingJo> CompactingJoes1
        {
            get
            {
                return global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.CompactingJoes1);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompactingJoes1_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySet, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.CommandSet, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Orders;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass>.Entry
                __EditableOrdersGridEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass>.Entry(
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeSavingEvent,
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeSavedEvent,
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeClosingEvent,
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeCreated,
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeActivated,
                    global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.__EditableOrdersGrid_InvokeSaveErrorEvent);
            private static void __EditableOrdersGrid_InvokeInitializeDataWorkspace(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.EditableOrdersGrid_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __EditableOrdersGrid_InvokeSavingEvent(global::LightSwitchApplication.EditableOrdersGrid s)
            {
                bool handled = false;
                s.EditableOrdersGrid_Saving(ref handled);
                return handled;
            }
            private static void __EditableOrdersGrid_InvokeSavedEvent(global::LightSwitchApplication.EditableOrdersGrid s)
            {
                s.EditableOrdersGrid_Saved();
            }
            private static bool __EditableOrdersGrid_InvokeClosingEvent(global::LightSwitchApplication.EditableOrdersGrid s)
            {
                bool cancel = false;
                s.EditableOrdersGrid_Closing(ref cancel);
                return cancel;
            }
            private static void __EditableOrdersGrid_InvokeCreated(global::LightSwitchApplication.EditableOrdersGrid s)
            {
                s.EditableOrdersGrid_Created();
            }
            private static void __EditableOrdersGrid_InvokeActivated(global::LightSwitchApplication.EditableOrdersGrid s)
            {
                s.EditableOrdersGrid_Activated();
            }
            private static bool __EditableOrdersGrid_InvokeSaveErrorEvent(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Exception ex)
            {
                bool handled = false;
                s.EditableOrdersGrid_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable OrdersQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                            global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                    this.Screen.DataWorkspace.OrderManagerDBData.Orders,
                                    "CommissionValueType"),
                                "Company"),
                            "Company1"),
                        "OrderStatu"),
                    "OrderThrough");
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ApprovalsQuery()
            {
                if (this.Screen.Orders.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Approval> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Approval>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Orders.SelectedItem.Details.Properties.Approvals).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Approvals1Query()
            {
                if (this.Screen.Orders.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Approval> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Approval>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Orders.SelectedItem.Details.Properties.Approvals).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable OrderCurrencyConversionsQuery()
            {
                if (this.Screen.Orders.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.OrderCurrencyConversion> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.OrderCurrencyConversion>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Orders.SelectedItem.Details.Properties.OrderCurrencyConversions).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CompactingJoesQuery()
            {
                if (this.Screen.Approvals.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CompactingJo> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CompactingJo>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Approvals.SelectedItem.Details.Properties.CompactingJoes).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CompactingJoes1Query()
            {
                if (this.Screen.Approvals1.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CompactingJo> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CompactingJo>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Approvals1.SelectedItem.Details.Properties.CompactingJoes).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Order>.Data _Orders;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Data _Approvals;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Data _Approvals1;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.OrderCurrencyConversion>.Data _OrderCurrencyConversions;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Data _CompactingJoes;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Data _CompactingJoes1;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Order> Orders
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Order>)base.GetItem(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Orders);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval> Approvals
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>)base.GetItem(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Approvals);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval> Approvals1
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>)base.GetItem(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.Approvals1);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.OrderCurrencyConversion> OrderCurrencyConversions
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.OrderCurrencyConversion>)base.GetItem(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.OrderCurrencyConversions);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo> CompactingJoes
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>)base.GetItem(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.CompactingJoes);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo> CompactingJoes1
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>)base.GetItem(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties.CompactingJoes1);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Order>.Entry
                    Orders = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Order>.Entry(
                        "Orders",
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Orders_Stub,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Orders_Validate,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Orders_CreateQuery,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Orders_SelectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Orders_OnCollectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Orders_OnLoaded);
                private static void _Orders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Order>.Data> c, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._Orders, sf);
                }
                private static void _Orders_Validate(global::LightSwitchApplication.EditableOrdersGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Orders_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Orders_CreateQuery(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object[] args)
                {
                    return d.OrdersQuery();
                }
                private static void _Orders_SelectionChanged(global::LightSwitchApplication.EditableOrdersGrid s)
                {
                    s.Orders_SelectionChanged();
                }
                private static void _Orders_OnCollectionChanged(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Orders_Changed(e);
                }
                private static void _Orders_OnLoaded(global::LightSwitchApplication.EditableOrdersGrid s, bool succeeded)
                {
                    s.Orders_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Entry
                    Approvals = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Entry(
                        "Approvals",
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals_Stub,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals_Validate,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals_CreateQuery,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals_SelectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals_OnCollectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals_OnLoaded);
                private static void _Approvals_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Data> c, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._Approvals, sf);
                }
                private static void _Approvals_Validate(global::LightSwitchApplication.EditableOrdersGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Approvals_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Approvals_CreateQuery(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object[] args)
                {
                    return d.ApprovalsQuery();
                }
                private static void _Approvals_SelectionChanged(global::LightSwitchApplication.EditableOrdersGrid s)
                {
                    s.Approvals_SelectionChanged();
                }
                private static void _Approvals_OnCollectionChanged(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Approvals_Changed(e);
                }
                private static void _Approvals_OnLoaded(global::LightSwitchApplication.EditableOrdersGrid s, bool succeeded)
                {
                    s.Approvals_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Entry
                    Approvals1 = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Entry(
                        "Approvals1",
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals1_Stub,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals1_Validate,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals1_CreateQuery,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals1_SelectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals1_OnCollectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._Approvals1_OnLoaded);
                private static void _Approvals1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.Approval>.Data> c, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._Approvals1, sf);
                }
                private static void _Approvals1_Validate(global::LightSwitchApplication.EditableOrdersGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Approvals1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Approvals1_CreateQuery(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object[] args)
                {
                    return d.Approvals1Query();
                }
                private static void _Approvals1_SelectionChanged(global::LightSwitchApplication.EditableOrdersGrid s)
                {
                    s.Approvals1_SelectionChanged();
                }
                private static void _Approvals1_OnCollectionChanged(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Approvals1_Changed(e);
                }
                private static void _Approvals1_OnLoaded(global::LightSwitchApplication.EditableOrdersGrid s, bool succeeded)
                {
                    s.Approvals1_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.OrderCurrencyConversion>.Entry
                    OrderCurrencyConversions = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.OrderCurrencyConversion>.Entry(
                        "OrderCurrencyConversions",
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._OrderCurrencyConversions_Stub,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._OrderCurrencyConversions_Validate,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._OrderCurrencyConversions_CreateQuery,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._OrderCurrencyConversions_SelectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._OrderCurrencyConversions_OnCollectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._OrderCurrencyConversions_OnLoaded);
                private static void _OrderCurrencyConversions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.OrderCurrencyConversion>.Data> c, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderCurrencyConversions, sf);
                }
                private static void _OrderCurrencyConversions_Validate(global::LightSwitchApplication.EditableOrdersGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.OrderCurrencyConversions_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _OrderCurrencyConversions_CreateQuery(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object[] args)
                {
                    return d.OrderCurrencyConversionsQuery();
                }
                private static void _OrderCurrencyConversions_SelectionChanged(global::LightSwitchApplication.EditableOrdersGrid s)
                {
                    s.OrderCurrencyConversions_SelectionChanged();
                }
                private static void _OrderCurrencyConversions_OnCollectionChanged(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.OrderCurrencyConversions_Changed(e);
                }
                private static void _OrderCurrencyConversions_OnLoaded(global::LightSwitchApplication.EditableOrdersGrid s, bool succeeded)
                {
                    s.OrderCurrencyConversions_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Entry
                    CompactingJoes = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Entry(
                        "CompactingJoes",
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes_Stub,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes_Validate,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes_CreateQuery,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes_SelectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes_OnCollectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes_OnLoaded);
                private static void _CompactingJoes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Data> c, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._CompactingJoes, sf);
                }
                private static void _CompactingJoes_Validate(global::LightSwitchApplication.EditableOrdersGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CompactingJoes_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CompactingJoes_CreateQuery(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object[] args)
                {
                    return d.CompactingJoesQuery();
                }
                private static void _CompactingJoes_SelectionChanged(global::LightSwitchApplication.EditableOrdersGrid s)
                {
                    s.CompactingJoes_SelectionChanged();
                }
                private static void _CompactingJoes_OnCollectionChanged(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CompactingJoes_Changed(e);
                }
                private static void _CompactingJoes_OnLoaded(global::LightSwitchApplication.EditableOrdersGrid s, bool succeeded)
                {
                    s.CompactingJoes_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Entry
                    CompactingJoes1 = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Entry(
                        "CompactingJoes1",
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes1_Stub,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes1_Validate,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes1_CreateQuery,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes1_SelectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes1_OnCollectionChanged,
                        global::LightSwitchApplication.EditableOrdersGrid.DetailsClass.PropertySetProperties._CompactingJoes1_OnLoaded);
                private static void _CompactingJoes1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditableOrdersGrid, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass, global::LightSwitchApplication.CompactingJo>.Data> c, global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._CompactingJoes1, sf);
                }
                private static void _CompactingJoes1_Validate(global::LightSwitchApplication.EditableOrdersGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CompactingJoes1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CompactingJoes1_CreateQuery(global::LightSwitchApplication.EditableOrdersGrid.DetailsClass d, object[] args)
                {
                    return d.CompactingJoes1Query();
                }
                private static void _CompactingJoes1_SelectionChanged(global::LightSwitchApplication.EditableOrdersGrid s)
                {
                    s.CompactingJoes1_SelectionChanged();
                }
                private static void _CompactingJoes1_OnCollectionChanged(global::LightSwitchApplication.EditableOrdersGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CompactingJoes1_Changed(e);
                }
                private static void _CompactingJoes1_OnLoaded(global::LightSwitchApplication.EditableOrdersGrid s, bool succeeded)
                {
                    s.CompactingJoes1_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
