

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class DyeingJoItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DyeingJoItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DyeingJoItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DyeingJoItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DyeingJoItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DyeingJoItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJoItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJoItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long DyeingJoItemsID
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJoItemsID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJoItemsID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJoItemsID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJoItemsID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Color
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.Color);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.Color, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Color_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Color_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Color_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string QualityDescription
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.QualityDescription);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.QualityDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QualityDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QualityDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QualityDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ReqGSM
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.ReqGSM);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.ReqGSM, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReqGSM_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReqGSM_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReqGSM_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ReqWidth
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.ReqWidth);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.ReqWidth, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReqWidth_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReqWidth_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReqWidth_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal NetQty
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.NetQty);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.NetQty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NetQty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NetQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NetQty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal RatePerKg
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.RatePerKg);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.RatePerKg, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RatePerKg_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RatePerKg_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RatePerKg_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.TotalAmount);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.TotalAmount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalAmount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalAmount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalAmount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.DyeingJO1 DyeingJO1
        {
            get
            {
                return global::LightSwitchApplication.DyeingJoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJO1);
            }
            set
            {
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJO1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJO1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJO1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJO1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DyeingJoItem,
                global::LightSwitchApplication.DyeingJoItem.DetailsClass,
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJoItemsID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>.Entry
                __DyeingJoItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.DyeingJoItem.DetailsClass.__DyeingJoItem_CreateNew,
                    global::LightSwitchApplication.DyeingJoItem.DetailsClass.__DyeingJoItem_Created,
                    global::LightSwitchApplication.DyeingJoItem.DetailsClass.__DyeingJoItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DyeingJoItem __DyeingJoItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DyeingJoItem> es)
            {
                return new global::LightSwitchApplication.DyeingJoItem(es);
            }
            private static void __DyeingJoItem_Created(global::LightSwitchApplication.DyeingJoItem e)
            {
                e.DyeingJoItem_Created();
            }
            private static bool __DyeingJoItem_AllowSaveWithErrors(global::LightSwitchApplication.DyeingJoItem e)
            {
                bool result = false;
                e.DyeingJoItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, long> DyeingJoItemsID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJoItemsID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string> Color
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.Color) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string> QualityDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.QualityDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string> ReqGSM
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.ReqGSM) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string> ReqWidth
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.ReqWidth) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal> NetQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.NetQty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal> RatePerKg
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.RatePerKg) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal> TotalAmount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.TotalAmount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::LightSwitchApplication.DyeingJO1> DyeingJO1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJO1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::LightSwitchApplication.DyeingJO1>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new long DyeingJoItemsID { get; }
                new string Color { get; set; }
                new string QualityDescription { get; set; }
                new string ReqGSM { get; set; }
                new string ReqWidth { get; set; }
                new decimal NetQty { get; set; }
                new decimal RatePerKg { get; set; }
                new decimal TotalAmount { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DyeingJO1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, long>.Entry
                    DyeingJoItemsID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, long>.Entry(
                        "DyeingJoItemsID",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJoItemsID_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJoItemsID_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJoItemsID_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJoItemsID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJoItemsID_OnValueChanged);
                private static void _DyeingJoItemsID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, long>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._DyeingJoItemsID, sf);
                }
                private static bool _DyeingJoItemsID_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.DyeingJoItemsID_IsReadOnly(ref result);
                    return result;
                }
                private static void _DyeingJoItemsID_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DyeingJoItemsID_Validate(r);
                }
                private static long _DyeingJoItemsID_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.DyeingJoItemsID;
                }
                private static void _DyeingJoItemsID_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.DyeingJoItemsID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry
                    Color = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry(
                        "Color",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._Color_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._Color_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._Color_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._Color_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._Color_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._Color_OnValueChanged);
                private static void _Color_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Color, sf);
                }
                private static bool _Color_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.Color_IsReadOnly(ref result);
                    return result;
                }
                private static void _Color_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Color_Validate(r);
                }
                private static string _Color_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Color;
                }
                private static void _Color_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Color = v;
                }
                private static void _Color_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.Color_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry
                    QualityDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry(
                        "QualityDescription",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._QualityDescription_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._QualityDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._QualityDescription_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._QualityDescription_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._QualityDescription_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._QualityDescription_OnValueChanged);
                private static void _QualityDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._QualityDescription, sf);
                }
                private static bool _QualityDescription_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.QualityDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _QualityDescription_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.QualityDescription_Validate(r);
                }
                private static string _QualityDescription_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.QualityDescription;
                }
                private static void _QualityDescription_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.QualityDescription = v;
                }
                private static void _QualityDescription_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.QualityDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry
                    ReqGSM = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry(
                        "ReqGSM",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqGSM_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqGSM_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqGSM_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqGSM_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqGSM_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqGSM_OnValueChanged);
                private static void _ReqGSM_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ReqGSM, sf);
                }
                private static bool _ReqGSM_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.ReqGSM_IsReadOnly(ref result);
                    return result;
                }
                private static void _ReqGSM_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ReqGSM_Validate(r);
                }
                private static string _ReqGSM_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ReqGSM;
                }
                private static void _ReqGSM_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ReqGSM = v;
                }
                private static void _ReqGSM_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.ReqGSM_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry
                    ReqWidth = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Entry(
                        "ReqWidth",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqWidth_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqWidth_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqWidth_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqWidth_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqWidth_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._ReqWidth_OnValueChanged);
                private static void _ReqWidth_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ReqWidth, sf);
                }
                private static bool _ReqWidth_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.ReqWidth_IsReadOnly(ref result);
                    return result;
                }
                private static void _ReqWidth_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ReqWidth_Validate(r);
                }
                private static string _ReqWidth_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ReqWidth;
                }
                private static void _ReqWidth_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ReqWidth = v;
                }
                private static void _ReqWidth_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.ReqWidth_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Entry
                    NetQty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Entry(
                        "NetQty",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._NetQty_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._NetQty_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._NetQty_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._NetQty_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._NetQty_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._NetQty_OnValueChanged);
                private static void _NetQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._NetQty, sf);
                }
                private static bool _NetQty_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.NetQty_IsReadOnly(ref result);
                    return result;
                }
                private static void _NetQty_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NetQty_Validate(r);
                }
                private static decimal _NetQty_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.NetQty;
                }
                private static void _NetQty_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.NetQty = v;
                }
                private static void _NetQty_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.NetQty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Entry
                    RatePerKg = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Entry(
                        "RatePerKg",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._RatePerKg_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._RatePerKg_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._RatePerKg_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._RatePerKg_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._RatePerKg_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._RatePerKg_OnValueChanged);
                private static void _RatePerKg_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RatePerKg, sf);
                }
                private static bool _RatePerKg_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.RatePerKg_IsReadOnly(ref result);
                    return result;
                }
                private static void _RatePerKg_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RatePerKg_Validate(r);
                }
                private static decimal _RatePerKg_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RatePerKg;
                }
                private static void _RatePerKg_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.RatePerKg = v;
                }
                private static void _RatePerKg_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.RatePerKg_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Entry
                    TotalAmount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Entry(
                        "TotalAmount",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._TotalAmount_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._TotalAmount_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._TotalAmount_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._TotalAmount_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._TotalAmount_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._TotalAmount_OnValueChanged);
                private static void _TotalAmount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._TotalAmount, sf);
                }
                private static bool _TotalAmount_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.TotalAmount_IsReadOnly(ref result);
                    return result;
                }
                private static void _TotalAmount_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TotalAmount_Validate(r);
                }
                private static decimal _TotalAmount_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.TotalAmount;
                }
                private static void _TotalAmount_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.TotalAmount = v;
                }
                private static void _TotalAmount_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.TotalAmount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::LightSwitchApplication.DyeingJO1>.Entry
                    DyeingJO1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::LightSwitchApplication.DyeingJO1>.Entry(
                        "DyeingJO1",
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_Stub,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_Validate,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_GetCoreImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_Refresh,
                        global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties._DyeingJO1_OnValueChanged);
                private static void _DyeingJO1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::LightSwitchApplication.DyeingJO1>.Data> c, global::LightSwitchApplication.DyeingJoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._DyeingJO1, sf);
                }
                private static bool _DyeingJO1_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJoItem e)
                {
                    bool result = false;
                    e.DyeingJO1_IsReadOnly(ref result);
                    return result;
                }
                private static void _DyeingJO1_Validate(global::LightSwitchApplication.DyeingJoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DyeingJO1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DyeingJO1_GetCoreImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.DyeingJO1;
                }
                private static global::LightSwitchApplication.DyeingJO1 _DyeingJO1_GetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJO1, ref d._DyeingJO1);
                }
                private static void _DyeingJO1_SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass d, global::LightSwitchApplication.DyeingJO1 v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJO1, ref d._DyeingJO1, (i, ev) => i.DyeingJO1 = ev, v);
                }
                private static void _DyeingJO1_Refresh(global::LightSwitchApplication.DyeingJoItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DyeingJoItem.DetailsClass.PropertySetProperties.DyeingJO1, ref d._DyeingJO1);
                }
                private static void _DyeingJO1_OnValueChanged(global::LightSwitchApplication.DyeingJoItem e)
                {
                    e.DyeingJO1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, long>.Data _DyeingJoItemsID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data _Color;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data _QualityDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data _ReqGSM;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, string>.Data _ReqWidth;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Data _NetQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Data _RatePerKg;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, decimal>.Data _TotalAmount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass, global::LightSwitchApplication.DyeingJO1>.Data _DyeingJO1;
            
        }
    
        #endregion
    }
    
    #endregion
}
