

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class DyeingJO1 : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DyeingJO1 entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DyeingJO1()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DyeingJO1(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DyeingJO1> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DyeingJO1.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJO1_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJO1_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long DyeingJOId
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJOId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJOId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJOId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DyeingJOId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SupplierID
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.SupplierID);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.SupplierID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SupplierID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SupplierID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SupplierID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long OrderID
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.OrderID);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.OrderID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long PurchaseOrderID
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.PurchaseOrderID);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.PurchaseOrderID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime JODate
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.JODate);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.JODate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JODate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JODate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JODate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string QuoteNo
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.QuoteNo);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.QuoteNo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuoteNo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuoteNo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuoteNo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime QuoteDate
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.QuoteDate);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.QuoteDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuoteDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuoteDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuoteDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string GRNRefNo
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.GRNRefNo);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.GRNRefNo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GRNRefNo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GRNRefNo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GRNRefNo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string OrderRef
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.OrderRef);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.OrderRef, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderRef_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderRef_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderRef_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Process
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.Process);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.Process, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Process_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Process_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Process_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TermsAndConditions
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.TermsAndConditions);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.TermsAndConditions, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermsAndConditions_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermsAndConditions_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TermsAndConditions_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal TotalValue
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.TotalValue);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.TotalValue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalValue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalValue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalValue_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long ApprovalID
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.ApprovalID);
            }
            set
            {
                global::LightSwitchApplication.DyeingJO1.DetailsClass.SetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.ApprovalID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApprovalID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApprovalID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApprovalID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.DyeingJoItem> DyeingJoItems
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetValue(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJoItems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DyeingJoItem> DyeingJoItemsQuery
        {
            get
            {
                return global::LightSwitchApplication.DyeingJO1.DetailsClass.GetQuery(this, global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJoItems);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DyeingJO1,
                global::LightSwitchApplication.DyeingJO1.DetailsClass,
                global::LightSwitchApplication.DyeingJO1.DetailsClass.IImplementation,
                global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJOId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>.Entry
                __DyeingJO1Entry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>.Entry(
                    global::LightSwitchApplication.DyeingJO1.DetailsClass.__DyeingJO1_CreateNew,
                    global::LightSwitchApplication.DyeingJO1.DetailsClass.__DyeingJO1_Created,
                    global::LightSwitchApplication.DyeingJO1.DetailsClass.__DyeingJO1_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DyeingJO1 __DyeingJO1_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DyeingJO1> es)
            {
                return new global::LightSwitchApplication.DyeingJO1(es);
            }
            private static void __DyeingJO1_Created(global::LightSwitchApplication.DyeingJO1 e)
            {
                e.DyeingJO1_Created();
            }
            private static bool __DyeingJO1_AllowSaveWithErrors(global::LightSwitchApplication.DyeingJO1 e)
            {
                bool result = false;
                e.DyeingJO1_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long> DyeingJOId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJOId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, int> SupplierID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.SupplierID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long> OrderID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.OrderID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long> PurchaseOrderID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.PurchaseOrderID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime> JODate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.JODate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string> QuoteNo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.QuoteNo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime> QuoteDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.QuoteDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string> GRNRefNo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.GRNRefNo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string> OrderRef
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.OrderRef) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string> Process
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.Process) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string> TermsAndConditions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.TermsAndConditions) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, decimal> TotalValue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.TotalValue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long> ApprovalID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.ApprovalID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::LightSwitchApplication.DyeingJoItem> DyeingJoItems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJoItems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::LightSwitchApplication.DyeingJoItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new long DyeingJOId { get; }
                new int SupplierID { get; set; }
                new long OrderID { get; set; }
                new long PurchaseOrderID { get; set; }
                new global::System.DateTime JODate { get; set; }
                new string QuoteNo { get; set; }
                new global::System.DateTime QuoteDate { get; set; }
                new string GRNRefNo { get; set; }
                new string OrderRef { get; set; }
                new string Process { get; set; }
                new string TermsAndConditions { get; set; }
                new decimal TotalValue { get; set; }
                new long ApprovalID { get; set; }
                new global::System.Collections.IEnumerable DyeingJoItems { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry
                    DyeingJOId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry(
                        "DyeingJOId",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJOId_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJOId_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJOId_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJOId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJOId_OnValueChanged);
                private static void _DyeingJOId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._DyeingJOId, sf);
                }
                private static bool _DyeingJOId_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.DyeingJOId_IsReadOnly(ref result);
                    return result;
                }
                private static void _DyeingJOId_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DyeingJOId_Validate(r);
                }
                private static long _DyeingJOId_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.DyeingJOId;
                }
                private static void _DyeingJOId_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.DyeingJOId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, int>.Entry
                    SupplierID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, int>.Entry(
                        "SupplierID",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._SupplierID_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._SupplierID_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._SupplierID_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._SupplierID_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._SupplierID_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._SupplierID_OnValueChanged);
                private static void _SupplierID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, int>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._SupplierID, sf);
                }
                private static bool _SupplierID_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.SupplierID_IsReadOnly(ref result);
                    return result;
                }
                private static void _SupplierID_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SupplierID_Validate(r);
                }
                private static int _SupplierID_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.SupplierID;
                }
                private static void _SupplierID_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SupplierID = v;
                }
                private static void _SupplierID_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.SupplierID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry
                    OrderID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry(
                        "OrderID",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderID_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderID_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderID_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderID_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderID_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderID_OnValueChanged);
                private static void _OrderID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderID, sf);
                }
                private static bool _OrderID_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.OrderID_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderID_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderID_Validate(r);
                }
                private static long _OrderID_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderID;
                }
                private static void _OrderID_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, long v)
                {
                    d.ImplementationEntity.OrderID = v;
                }
                private static void _OrderID_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.OrderID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry
                    PurchaseOrderID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry(
                        "PurchaseOrderID",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._PurchaseOrderID_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._PurchaseOrderID_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._PurchaseOrderID_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._PurchaseOrderID_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._PurchaseOrderID_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._PurchaseOrderID_OnValueChanged);
                private static void _PurchaseOrderID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._PurchaseOrderID, sf);
                }
                private static bool _PurchaseOrderID_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.PurchaseOrderID_IsReadOnly(ref result);
                    return result;
                }
                private static void _PurchaseOrderID_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PurchaseOrderID_Validate(r);
                }
                private static long _PurchaseOrderID_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.PurchaseOrderID;
                }
                private static void _PurchaseOrderID_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, long v)
                {
                    d.ImplementationEntity.PurchaseOrderID = v;
                }
                private static void _PurchaseOrderID_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.PurchaseOrderID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Entry
                    JODate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Entry(
                        "JODate",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._JODate_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._JODate_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._JODate_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._JODate_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._JODate_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._JODate_OnValueChanged);
                private static void _JODate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._JODate, sf);
                }
                private static bool _JODate_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.JODate_IsReadOnly(ref result);
                    return result;
                }
                private static void _JODate_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JODate_Validate(r);
                }
                private static global::System.DateTime _JODate_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.JODate;
                }
                private static void _JODate_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.JODate = global::LightSwitchApplication.DyeingJO1.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _JODate_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.JODate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry
                    QuoteNo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry(
                        "QuoteNo",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteNo_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteNo_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteNo_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteNo_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteNo_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteNo_OnValueChanged);
                private static void _QuoteNo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._QuoteNo, sf);
                }
                private static bool _QuoteNo_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.QuoteNo_IsReadOnly(ref result);
                    return result;
                }
                private static void _QuoteNo_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.QuoteNo_Validate(r);
                }
                private static string _QuoteNo_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.QuoteNo;
                }
                private static void _QuoteNo_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, string v)
                {
                    d.ImplementationEntity.QuoteNo = v;
                }
                private static void _QuoteNo_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.QuoteNo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Entry
                    QuoteDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Entry(
                        "QuoteDate",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteDate_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteDate_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteDate_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteDate_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._QuoteDate_OnValueChanged);
                private static void _QuoteDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._QuoteDate, sf);
                }
                private static bool _QuoteDate_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.QuoteDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _QuoteDate_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.QuoteDate_Validate(r);
                }
                private static global::System.DateTime _QuoteDate_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.QuoteDate;
                }
                private static void _QuoteDate_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.QuoteDate = global::LightSwitchApplication.DyeingJO1.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _QuoteDate_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.QuoteDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry
                    GRNRefNo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry(
                        "GRNRefNo",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._GRNRefNo_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._GRNRefNo_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._GRNRefNo_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._GRNRefNo_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._GRNRefNo_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._GRNRefNo_OnValueChanged);
                private static void _GRNRefNo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._GRNRefNo, sf);
                }
                private static bool _GRNRefNo_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.GRNRefNo_IsReadOnly(ref result);
                    return result;
                }
                private static void _GRNRefNo_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.GRNRefNo_Validate(r);
                }
                private static string _GRNRefNo_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.GRNRefNo;
                }
                private static void _GRNRefNo_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, string v)
                {
                    d.ImplementationEntity.GRNRefNo = v;
                }
                private static void _GRNRefNo_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.GRNRefNo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry
                    OrderRef = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry(
                        "OrderRef",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderRef_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderRef_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderRef_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderRef_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderRef_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._OrderRef_OnValueChanged);
                private static void _OrderRef_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderRef, sf);
                }
                private static bool _OrderRef_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.OrderRef_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderRef_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderRef_Validate(r);
                }
                private static string _OrderRef_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderRef;
                }
                private static void _OrderRef_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, string v)
                {
                    d.ImplementationEntity.OrderRef = v;
                }
                private static void _OrderRef_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.OrderRef_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry
                    Process = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry(
                        "Process",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._Process_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._Process_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._Process_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._Process_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._Process_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._Process_OnValueChanged);
                private static void _Process_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._Process, sf);
                }
                private static bool _Process_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.Process_IsReadOnly(ref result);
                    return result;
                }
                private static void _Process_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Process_Validate(r);
                }
                private static string _Process_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.Process;
                }
                private static void _Process_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Process = v;
                }
                private static void _Process_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.Process_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry
                    TermsAndConditions = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Entry(
                        "TermsAndConditions",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TermsAndConditions_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TermsAndConditions_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TermsAndConditions_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TermsAndConditions_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TermsAndConditions_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TermsAndConditions_OnValueChanged);
                private static void _TermsAndConditions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._TermsAndConditions, sf);
                }
                private static bool _TermsAndConditions_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.TermsAndConditions_IsReadOnly(ref result);
                    return result;
                }
                private static void _TermsAndConditions_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TermsAndConditions_Validate(r);
                }
                private static string _TermsAndConditions_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.TermsAndConditions;
                }
                private static void _TermsAndConditions_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TermsAndConditions = v;
                }
                private static void _TermsAndConditions_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.TermsAndConditions_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, decimal>.Entry
                    TotalValue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, decimal>.Entry(
                        "TotalValue",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TotalValue_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TotalValue_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TotalValue_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TotalValue_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TotalValue_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._TotalValue_OnValueChanged);
                private static void _TotalValue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._TotalValue, sf);
                }
                private static bool _TotalValue_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.TotalValue_IsReadOnly(ref result);
                    return result;
                }
                private static void _TotalValue_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TotalValue_Validate(r);
                }
                private static decimal _TotalValue_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.TotalValue;
                }
                private static void _TotalValue_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.TotalValue = v;
                }
                private static void _TotalValue_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.TotalValue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry
                    ApprovalID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Entry(
                        "ApprovalID",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._ApprovalID_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._ApprovalID_ComputeIsReadOnly,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._ApprovalID_Validate,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._ApprovalID_GetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._ApprovalID_SetImplementationValue,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._ApprovalID_OnValueChanged);
                private static void _ApprovalID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._ApprovalID, sf);
                }
                private static bool _ApprovalID_ComputeIsReadOnly(global::LightSwitchApplication.DyeingJO1 e)
                {
                    bool result = false;
                    e.ApprovalID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ApprovalID_Validate(global::LightSwitchApplication.DyeingJO1 e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ApprovalID_Validate(r);
                }
                private static long _ApprovalID_GetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.ApprovalID;
                }
                private static void _ApprovalID_SetImplementationValue(global::LightSwitchApplication.DyeingJO1.DetailsClass d, long v)
                {
                    d.ImplementationEntity.ApprovalID = v;
                }
                private static void _ApprovalID_OnValueChanged(global::LightSwitchApplication.DyeingJO1 e)
                {
                    e.ApprovalID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::LightSwitchApplication.DyeingJoItem>.Entry
                    DyeingJoItems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::LightSwitchApplication.DyeingJoItem>.Entry(
                        "DyeingJoItems",
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJoItems_Stub,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJoItems_GetReferencedEntities,
                        global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties._DyeingJoItems_GetEntityCollection);
                private static void _DyeingJoItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DyeingJO1.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::LightSwitchApplication.DyeingJoItem>.Data> c, global::LightSwitchApplication.DyeingJO1.DetailsClass d, object sf)
                {
                    c(d, ref d._DyeingJoItems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.DyeingJoItem> _DyeingJoItems_GetReferencedEntities(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.DyeingJoItem, global::LightSwitchApplication.DyeingJoItem.DetailsClass>(global::LightSwitchApplication.DyeingJO1.DetailsClass.PropertySetProperties.DyeingJoItems, ref d._DyeingJoItems);
                }
                private static global::System.Collections.IEnumerable _DyeingJoItems_GetEntityCollection(global::LightSwitchApplication.DyeingJO1.DetailsClass d)
                {
                    return d.ImplementationEntity.DyeingJoItems;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data _DyeingJOId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, int>.Data _SupplierID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data _OrderID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data _PurchaseOrderID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Data _JODate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data _QuoteNo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::System.DateTime>.Data _QuoteDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data _GRNRefNo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data _OrderRef;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data _Process;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, string>.Data _TermsAndConditions;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, decimal>.Data _TotalValue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, long>.Data _ApprovalID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DyeingJO1, global::LightSwitchApplication.DyeingJO1.DetailsClass, global::LightSwitchApplication.DyeingJoItem>.Data _DyeingJoItems;
            
        }
    
        #endregion
    }
    
    #endregion
}
