//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class OrderManagerDBDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::OrderManagerDBData.Implementation.OrderManagerDBDataObjectContext>
    {
    
        public OrderManagerDBDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().OrderManagerDBData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class OrderManagerDBDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::OrderManagerDBData.Implementation.OrderManagerDBDataObjectContext>
    {
        public OrderManagerDBDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::OrderManagerDBData.Implementation.DyeingJO))
            {
                return new global::OrderManagerDBData.Implementation.DyeingJO();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::OrderManagerDBData.Implementation.OrderManagerDBDataObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::OrderManagerDBData.Implementation.OrderManagerDBDataObjectContext(base.GetEntityConnectionString(
                "OrderManagerDBData", 
                "res://" + assemblyName + "/OrderManagerDBData.csdl|res://" + assemblyName + "/OrderManagerDBData.ssdl|res://" + assemblyName + "/OrderManagerDBData.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.DyeingJO))
            {
                return new global::OrderManagerDBData.Implementation.DyeingJO();
            }
            return null;
        }
    
    #endregion
    
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class OrderManagerDBData1DataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::OrderManagerDBData1.Implementation.OrderManagerDBData1ObjectContext>
    {
    
        public OrderManagerDBData1DataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().OrderManagerDBData1;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class OrderManagerDBData1ServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::OrderManagerDBData1.Implementation.OrderManagerDBData1ObjectContext>
    {
        public OrderManagerDBData1ServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::OrderManagerDBData1.Implementation.DyeingJO1))
            {
                return new global::OrderManagerDBData1.Implementation.DyeingJO1();
            }
            if (type == typeof(global::OrderManagerDBData1.Implementation.DyeingJoItem))
            {
                return new global::OrderManagerDBData1.Implementation.DyeingJoItem();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::OrderManagerDBData1.Implementation.OrderManagerDBData1ObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::OrderManagerDBData1.Implementation.OrderManagerDBData1ObjectContext(base.GetEntityConnectionString(
                "OrderManagerDBData1", 
                "res://" + assemblyName + "/OrderManagerDBData1.csdl|res://" + assemblyName + "/OrderManagerDBData1.ssdl|res://" + assemblyName + "/OrderManagerDBData1.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.DyeingJO1))
            {
                return new global::OrderManagerDBData1.Implementation.DyeingJO1();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DyeingJoItem))
            {
                return new global::OrderManagerDBData1.Implementation.DyeingJoItem();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.OrderManagerDBData))
            {
                return new global::LightSwitchApplication.OrderManagerDBDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.OrderManagerDBData1))
            {
                return new global::LightSwitchApplication.OrderManagerDBData1Service();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.OrderManagerDBData))
            {
                return new global::LightSwitchApplication.Implementation.OrderManagerDBDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.OrderManagerDBData1))
            {
                return new global::LightSwitchApplication.Implementation.OrderManagerDBData1ServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.DyeingJO) == definitionType)
            {
                return typeof(global::OrderManagerDBData.Implementation.DyeingJO);
            }
            if (typeof(global::LightSwitchApplication.DyeingJO1) == definitionType)
            {
                return typeof(global::OrderManagerDBData1.Implementation.DyeingJO1);
            }
            if (typeof(global::LightSwitchApplication.DyeingJoItem) == definitionType)
            {
                return typeof(global::OrderManagerDBData1.Implementation.DyeingJoItem);
            }
            return null;
        }
    }
}

namespace OrderManagerDBData.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DyeingJO :
        global::LightSwitchApplication.DyeingJO.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

namespace OrderManagerDBData1.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DyeingJO1 :
        global::LightSwitchApplication.DyeingJO1.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.DyeingJO1.DetailsClass.IImplementation.DyeingJoItems
        {
            get
            {
                return this.DyeingJoItems;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DyeingJoItem :
        global::LightSwitchApplication.DyeingJoItem.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DyeingJoItem.DetailsClass.IImplementation.DyeingJO1
        {
            get
            {
                return this.DyeingJO1;
            }
            set
            {
                this.DyeingJO1 = (global::OrderManagerDBData1.Implementation.DyeingJO1)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DyeingJO1");
                }
            }
        }
        
        partial void OnDyeingJOIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DyeingJO1");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

