//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandName
    {
        public BrandName()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public int BrandNameID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
