//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionValueType
    {
        public CommissionValueType()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public byte CommissionValueTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
