//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.OrderCurrencyConversions = new HashSet<OrderCurrencyConversion>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.ProductExtraCosts = new HashSet<ProductExtraCost>();
            this.ProductMaterialItems = new HashSet<ProductMaterialItem>();
            this.ProductMaterials = new HashSet<ProductMaterial>();
        }
    
        public short CurrencyID { get; set; }
        public string CountryName { get; set; }
        public string Symbol { get; set; }
    
        public virtual ICollection<OrderCurrencyConversion> OrderCurrencyConversions { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<ProductExtraCost> ProductExtraCosts { get; set; }
        public virtual ICollection<ProductMaterialItem> ProductMaterialItems { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterials { get; set; }
    }
}
