//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrderTolerance
    {
        public long JobOrderToleranceID { get; set; }
        public byte JobOrderToleraceTypeID { get; set; }
        public decimal ToleranceValueInPercentage { get; set; }
        public long OrderID { get; set; }
    
        public virtual JobOrderToleranceType JobOrderToleranceType { get; set; }
        public virtual Order Order { get; set; }
    }
}
