//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrderToleranceType
    {
        public JobOrderToleranceType()
        {
            this.JobOrderTolerances = new HashSet<JobOrderTolerance>();
        }
    
        public byte JobOrderToleranceTypeID { get; set; }
        public string Type { get; set; }
        public decimal DefaultToleranceInPercentage { get; set; }
    
        public virtual ICollection<JobOrderTolerance> JobOrderTolerances { get; set; }
    }
}
