//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialName
    {
        public MaterialName()
        {
            this.ProductMaterials = new HashSet<ProductMaterial>();
            this.SubMaterials = new HashSet<SubMaterial>();
        }
    
        public int MaterialNameID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductMaterial> ProductMaterials { get; set; }
        public virtual ICollection<SubMaterial> SubMaterials { get; set; }
    }
}
