//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReportCard
    {
        public long OrderReportCardID { get; set; }
        public byte OrderReportCardTypeID { get; set; }
        public decimal ProgressPercentage { get; set; }
        public long OrderID { get; set; }
        public Nullable<System.DateTime> RequiredFinishDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderReportCardType OrderReportCardType { get; set; }
    }
}
