//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CartonBoxes = new HashSet<CartonBox>();
            this.Histories = new HashSet<History>();
            this.Invoices = new HashSet<Invoice>();
            this.JobOrderTolerances = new HashSet<JobOrderTolerance>();
            this.MaterialsFromStocks = new HashSet<MaterialsFromStock>();
            this.OrderCurrencyConversions = new HashSet<OrderCurrencyConversion>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.OrderReportCards = new HashSet<OrderReportCard>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public long OrderID { get; set; }
        public int CustomerID { get; set; }
        public int OrderByID { get; set; }
        public byte OrderThoughID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<byte> CommissionValueTypeID { get; set; }
        public short OrderStatusID { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<decimal> TotalOrderValue { get; set; }
        public Nullable<System.DateTime> InternalDeliveryDate { get; set; }
        public Nullable<System.DateTime> OrderApprovedDate { get; set; }
        public Nullable<System.DateTime> OrderConfirmedDate { get; set; }
        public string CustomerOrderNumber { get; set; }
    
        public virtual ICollection<CartonBox> CartonBoxes { get; set; }
        public virtual CommissionValueType CommissionValueType { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<JobOrderTolerance> JobOrderTolerances { get; set; }
        public virtual ICollection<MaterialsFromStock> MaterialsFromStocks { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual OrderThrough OrderThrough { get; set; }
        public virtual ICollection<OrderCurrencyConversion> OrderCurrencyConversions { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<OrderReportCard> OrderReportCards { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
