//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public long PackageID { get; set; }
        public decimal Packed { get; set; }
        public decimal Pending { get; set; }
        public System.DateTime Date { get; set; }
        public long ProductBreakUpSummaryID { get; set; }
        public Nullable<decimal> ExcessToStock { get; set; }
    
        public virtual ProductBreakUpSummary ProductBreakUpSummary { get; set; }
    }
}
