//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExtraCost
    {
        public long ExtraCostID { get; set; }
        public long ProductID { get; set; }
        public short ExtraCostTypeID { get; set; }
        public Nullable<short> CurrencyID { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual ProductExtraCostType ProductExtraCostType { get; set; }
    }
}
