//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterialItem
    {
        public ProductMaterialItem()
        {
            this.OrderedItems = new HashSet<OrderedItem>();
        }
    
        public long ProductMaterialItemID { get; set; }
        public long MaterialID { get; set; }
        public long SubMaterialNameID { get; set; }
        public string Alias { get; set; }
        public decimal Quantity { get; set; }
        public short UOMID { get; set; }
        public short CurrencyID { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> LastPOGeneratedOn { get; set; }
        public decimal TaxInINR { get; set; }
        public Nullable<long> PurchaseOrderID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<OrderedItem> OrderedItems { get; set; }
        public virtual ProductMaterial ProductMaterial { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual SubMaterial SubMaterial { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
    }
}
