//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExtraCostType
    {
        public ProductExtraCostType()
        {
            this.ProductExtraCosts = new HashSet<ProductExtraCost>();
        }
    
        public short ExtraCostTypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<ProductExtraCost> ProductExtraCosts { get; set; }
    }
}
