//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCountryWiseBreakUp
    {
        public long ProductCountryWiseBreakUpID { get; set; }
        public string Country { get; set; }
        public decimal NumberOfPieces { get; set; }
        public Nullable<decimal> LS { get; set; }
        public Nullable<decimal> S { get; set; }
        public Nullable<decimal> M { get; set; }
        public Nullable<decimal> L { get; set; }
        public Nullable<decimal> XL { get; set; }
        public Nullable<decimal> XXL { get; set; }
        public Nullable<decimal> XXXL { get; set; }
        public long ProductBreakUpID { get; set; }
    
        public virtual ProductBreakUp ProductBreakUp { get; set; }
    }
}
