//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordermanager.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMaterial
    {
        public SubMaterial()
        {
            this.ProductMaterialItems = new HashSet<ProductMaterialItem>();
        }
    
        public long SubMaterialsNameID { get; set; }
        public long MaterialID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductMaterialItem> ProductMaterialItems { get; set; }
        public virtual ProductMaterial ProductMaterial { get; set; }
    }
}
